[package]
name = "ssh_infoget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = "2.7.1"
ssh2 = "0.9.4"
